# <span style="color:red"> Introduction to NumPy, Pandas and Matplotlib </span>

## <span style="color:blue"> Data Analysis </span>

Data Analysis is a process of inspecting, cleaning, transforming, and modeling data with the goal of discovering useful information, suggesting conclusions, and supporting decision-making.

Stpes for Data Analysis, Data Manipulation and Data Visualization:
1. Tranform Raw Data in a Desired Format 
2. Clean the Transformed Data (Step 1 and 2 also called as a Pre-processing of Data)
3. Prepare a Model
4. Analyse Trends and Make Decisions

## <span style="color:blue"> NumPy </span>

NumPy is a package for scientific computing.
1. Multi dimensional array
2. Methods for processing arrays
3. Element by element operations
4. Mathematical operations like logical, Fourier transform, shape manipulation, linear algebra and random number generation

In [6]:
print("Hello world")

Hello world


In [7]:
import numpy as np

### <span style="color:orange"> Ndarray - NumPy Array </span>

The ndarray is a multi-dimensional array object consisting of two parts -- the actual data, some metadata which describes the stored data. They are indexed just like sequence are in Python, starting from 0
1. Each element in ndarray is an object of data-type object called dtype
2. An item extracted from ndarray, is represented by a Python object of an array scalar type

### <span style="color:green"> Single Dimensional Array </span>

### <span style="color:orange"> Creating a Numpy Array </span>

In [8]:
# Creating a single-dimensional array
a = np.array([1,2,3]) # Calling the array function
print(a)

[1 2 3]


In [15]:
print(a.shape)
print(a.ndim)

(3,)
1


In [23]:
# Creating a multi-dimensional array
# Each set of elements within a square bracket indicates a row
# Array of two rows and two columns
b = np.array([[1,2], [3,4]])
print(b)

[[1 2]
 [3 4]]


In [18]:
print(b.shape)
print(b.ndim)

(2, 2)
2


In [19]:
# Creating an ndarray by wrapping a list
list1 = [1,2,3,4,5] # Creating a list
arr = np.array(list1) # Wrapping the list
print(arr)

[1 2 3 4 5]


In [20]:
arr.shape

(5,)

In [24]:
# Creating an array of numbers of a specified range
arr1 = np.arange(10, 100) # Array of numbers from 10 up to and excluding 100
print(arr1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


In [25]:
arr2 = np.arange(1,101)

In [27]:
arr2

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [28]:
# Creating a 5x5 array of zeroes
arr2 = np.zeros((5,5))
print(arr2)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [30]:
arrx = np.zeros(np.shape(arr2))

In [31]:
arrx

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [32]:
arrx == arr2

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [33]:
# Creating a linearly spaced vector, with spacing
vector = np.linspace(0, 20, 5) # Start, stop, Size
print(vector)

[ 0.  5. 10. 15. 20.]


In [43]:
vector2 = np.linspace(0,10,2) # It is not step, it is Size of the linear vector!

In [45]:
print(vector2)

[ 0. 10.]


In [46]:
vector2

array([ 0., 10.])

In [48]:
vector3 = np.linspace(0,10,4)
print(vector3)

[ 0.          3.33333333  6.66666667 10.        ]


In [49]:
# Creating Arrays from Existing Data
x = [1,2,3]
# Used for converting Python sequences into ndarrays
c = np.asarray(x) #np.asarray(a, dtype = None, order = None)
print(c)

[1 2 3]


In [57]:
e = np.asarray(x, dtype='float32')

In [58]:
e

array([1., 2., 3.], dtype=float32)

In [59]:
d = np.array(x)
print(d)

[1 2 3]


In [52]:
d = np.asarray(x)
print(d)

[1 2 3]


### <span style="color:red"> Key Differences: np.array() vs np.asarray() </span>

In [53]:
# 1. COPYING BEHAVIOR - The main difference
# np.array() ALWAYS creates a new copy
# np.asarray() creates a copy ONLY if needed

# Example with a regular Python list
my_list = [1, 2, 3, 4, 5]

# Both create arrays from the list (both make copies since input is not already an ndarray)
arr1 = np.array(my_list)
arr2 = np.asarray(my_list)

print("Original list:", my_list)
print("np.array result:", arr1)
print("np.asarray result:", arr2)
print("Are they equal?", np.array_equal(arr1, arr2))

Original list: [1, 2, 3, 4, 5]
np.array result: [1 2 3 4 5]
np.asarray result: [1 2 3 4 5]
Are they equal? True


In [64]:
alist = [1,2,3,4,5,6]

blist = [[1,2], [3,4]]

arr2 = np.array(alist)
arr1 =  np.asarray(blist, order='F')

In [65]:
print(arr2)
print(arr1)
print(arr1.shape)

[1 2 3 4 5 6]
[[1 2]
 [3 4]]
(2, 2)


In [54]:
# 2. THE KEY DIFFERENCE: When input is already a NumPy array
existing_array = np.array([10, 20, 30, 40])

# np.array() creates a NEW copy
new_copy = np.array(existing_array)

# np.asarray() returns the SAME array (no copy if not needed)
same_array = np.asarray(existing_array)

print("Original array:", existing_array)
print("New copy from np.array():", new_copy)
print("Same array from np.asarray():", same_array)

# Test if they are the same object in memory
print("\nMemory comparison:")
print("existing_array is new_copy:", existing_array is new_copy)
print("existing_array is same_array:", existing_array is same_array)

# Let's modify the original and see what happens
existing_array[0] = 999

print("\nAfter modifying original array:")
print("Original array:", existing_array)
print("New copy (unchanged):", new_copy)
print("Same array (changed too!):", same_array)

Original array: [10 20 30 40]
New copy from np.array(): [10 20 30 40]
Same array from np.asarray(): [10 20 30 40]

Memory comparison:
existing_array is new_copy: False
existing_array is same_array: True

After modifying original array:
Original array: [999  20  30  40]
New copy (unchanged): [10 20 30 40]
Same array (changed too!): [999  20  30  40]


In [55]:
# 3. Performance implications
import time

# Create a large array
large_array = np.random.rand(1000000)

# Time np.array() - always copies
start = time.time()
for _ in range(100):
    copy_result = np.array(large_array)
array_time = time.time() - start

# Time np.asarray() - no copy needed
start = time.time()
for _ in range(100):
    asarray_result = np.asarray(large_array)
asarray_time = time.time() - start

print(f"Time for 100 np.array() calls: {array_time:.4f} seconds")
print(f"Time for 100 np.asarray() calls: {asarray_time:.4f} seconds")
print(f"np.asarray() is {array_time/asarray_time:.1f}x faster when no copy is needed!")

Time for 100 np.array() calls: 0.1333 seconds
Time for 100 np.asarray() calls: 0.0001 seconds
np.asarray() is 1548.6x faster when no copy is needed!


In [56]:
# 4. When np.asarray() DOES create a copy
# Case 1: Different dtype
int_array = np.array([1, 2, 3, 4], dtype=int)
float_array = np.asarray(int_array, dtype=float)  # Forces a copy due to dtype change

print("Original int array:", int_array)
print("Float array from asarray:", float_array)
print("Are they the same object?", int_array is float_array)

# Case 2: Different order (C vs Fortran)
c_array = np.array([[1, 2], [3, 4]], order='C')
f_array = np.asarray(c_array, order='F')  # Forces a copy due to order change

print("\nOriginal C-order array:", c_array)
print("Fortran-order array:", f_array)
print("Are they the same object?", c_array is f_array)

Original int array: [1 2 3 4]
Float array from asarray: [1. 2. 3. 4.]
Are they the same object? False

Original C-order array: [[1 2]
 [3 4]]
Fortran-order array: [[1 2]
 [3 4]]
Are they the same object? False


### <span style="color:green"> Summary: When to use which? </span>

**Use `np.array()`:**
- When you **always want a copy** (safe for modifications)
- When you want to **ensure data independence**
- When working with **mixed data types** or **converting data types**

**Use `np.asarray()`:**
- When you want **maximum efficiency** (avoid unnecessary copies)
- When you **don't mind sharing memory** with the original
- In **function parameters** where input might already be an array
- When you want to **preserve the original if it's already a compatible array**

**Key Rule:** `np.asarray()` is **more efficient** but **potentially less safe**, while `np.array()` is **always safe** but **potentially less efficient**.

In [ ]:
# Converting a linear array of 8 elements into a 2x2x2 3D array
arr3 = np.zeros(8) # Flat array of eight zeroes
arr3d = arr3.reshape((2,2,2)) # Restructured array
print(arr3d)

In [66]:
arr3 = np.zeros(8)

In [67]:
arr3d = arr3.reshape(2,2,2)

In [68]:
arr3

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [69]:
arr3d

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [70]:
arr4d = arr3.reshape(2,2,2,2) # More than expected eles

ValueError: cannot reshape array of size 8 into shape (2,2,2,2)

In [71]:
arr2d = arr3.reshape(2,2) # Less than..

ValueError: cannot reshape array of size 8 into shape (2,2)

In [ ]:
# Needs to be an exact multiple

In [76]:
# Flatten rgw 3d array to get back the linear array
arr4 = arr3d.ravel()
print(arr4)

[0. 0. 0. 0. 0. 0. 0. 0.]


In [77]:
arrx = arr3d.ravel()
arrx

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [78]:
arry = arr3d.flatten()

In [79]:
arry

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [80]:
np.shares_memory(arrx, arr3d)

True

In [81]:
np.shares_memory(arry, arr3d)

False

In [82]:
arrx[1] = 1;
arr3d

array([[[0., 1.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [83]:
arr3d[1,1,-1] = 2
arrx

array([0., 1., 0., 0., 0., 0., 0., 2.])

In [ ]:
# flatten copies, ravel creates a view

### <span style="color:orange"> Indexing of NumPy Arrays </span>

In [84]:
# NumPy array indexing is identical to Python's indexing scheme
arr5 = np.arange(2, 20)
element = arr5[6]
print(element)

8


In [86]:
arr5 # R is exclusive

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [87]:
# Python's concept of lists slicing is extended to NumPy.
# The slice object is constructed by providing start, stop, and step parameters to slice()
arr6 = np.arange(20)
arr_slice = slice(1, 10, 2) # Start, stop & step
element2 = arr6[6]
print(arr6[arr_slice])

[1 3 5 7 9]


In [93]:
lst = [1,2,3,4,5,6,7,8,9,0]
sl = slice(1,10,2)
sl

slice(1, 10, 2)

In [94]:
lst[sl]

[2, 4, 6, 8, 0]

In [102]:
lst

[1, 2, 3, 4, 5, 6, 7, 8, 9, 0]

In [95]:
arr6[slice(1,10,2)]

array([1, 3, 5, 7, 9])

In [107]:
lst[1:10:2]

[2, 4, 6, 8, 0]

In [109]:
lst[1::2]

[2, 4, 6, 8, 0]

In [111]:
lst[::2]

[1, 3, 5, 7, 9]

In [112]:
lst[0::]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 0]

In [110]:
arr6[1:10:2]

array([1, 3, 5, 7, 9])

In [96]:
# Slicing items beginning with a specified index
arr7 = np.arange(20)
print(arr7[2:])

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:
# Slicing items until a specified index
print(arr7[:15])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [117]:
a = d[2:5,4:5]
a

array([], shape=(1, 0), dtype=int64)

In [114]:
# Extracting specific rows and columns using Slicing
d = np.array([[1,2,3], [3,4,5], [4,5,6]])
print(d[0:2, 0:2]) # Slice the first two rows and the first two columns

[[1 2]
 [3 4]]


### <span style="color:orange"> NumPy Array Attributes </span>

In [ ]:
print(d.shape) # Returns a tuple consisting of array dimensions
print(d.ndim) # Attribute returns the number of array dimensions
print(a.itemsize) # Returns the length of each element of array in bytes

(3, 3)
2
8


In [121]:
print(a.dtype)

int64


In [123]:
y = np.empty([3,2], dtype = int) # Creates an uninitialized array of specified shape and dtype
print(y)

[[1 2]
 [3 4]
 [5 6]]


In [124]:
u = np.empty([10,10], dtype= 'int8')
print(u)

[[  6  45  60  58   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0 105   0   0   0]
 [ 48  48  52  51  49  99  51  99  99  51]
 [ 57  52  55  97  53  55  54  53 100  54]
 [ 48  49  97  48  51  97 101  99  48  49]
 [ 52  52  98  48 101  48  56  48  50 102]
 [ 54  52  54  52 101  54  97  50  97  49]
 [ 57  52  99  99  50 101 112   0   0   0]]


In [130]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [131]:
np.ones([1,2])

array([[1., 1.]])

In [139]:
u = np.zeros((1,2,3))
u

array([[[0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
# Returns a new array of specified size, filled with zeros
z = np.zeros(5) # np.zeros(shape, dtype = float)
print(z)

In [133]:
np.random.rand(3,4)

array([[0.71112851, 0.28785275, 0.57529314, 0.37113068],
       [0.3789732 , 0.65314137, 0.11494585, 0.84429018],
       [0.1299805 , 0.50944769, 0.55436416, 0.72148937]])

In [136]:
u = np.random.randn(3,4) #Normal dist mean 0 std 1
sig = 3
mu = 5
u * sig + mu

array([[7.37262943, 8.27131023, 5.98777407, 2.75114182],
       [6.76954687, 3.30751728, 3.91540544, 9.35750587],
       [5.93914845, 7.54819396, 3.69888299, 4.76168374]])

In [138]:
np.ndarray((1,2))

array([[1., 1.]])

In [7]:
import numpy as np

In [ ]:
x = np.array([[1,2,3,4,5,6]])
y = np.array([[1,],[2,],[3,]])
print(x.shape)
print(y.shape)
print(x*y)
print(np.matmul(y,x))

(1, 6)
(3, 1)
[[ 1  2  3  4  5  6]
 [ 2  4  6  8 10 12]
 [ 3  6  9 12 15 18]]
[[ 1  2  3  4  5  6]
 [ 2  4  6  8 10 12]
 [ 3  6  9 12 15 18]]


In [18]:
print(x)
print(x >= 4)
print(x[x >= 4])
print(x.shape)
print(x[x >= 4].shape)


[[1 2 3 4 5 6]]
[[False False False  True  True  True]]
[4 5 6]
(1, 6)
(3,)


In [ ]:
print(y)
print(y % 2)
print(y[y%2 == 1])


print(np.mean(y))
print(np.sum(y))
print(np.var(y))

[[1]
 [2]
 [3]]
[[1]
 [0]
 [1]]
[1 3]
2.0
6
0.6666666666666666


In [36]:
print(y)

[[1]
 [2]
 [3]]


In [37]:
print(y%2)

[[1]
 [0]
 [1]]


In [35]:
print(y[y%2])


[[[2]]

 [[1]]

 [[2]]]


In [38]:
print(x)

[[1 2 3 4 5 6]]


In [39]:
a = np.asarray([[1,2],[3,4]])

In [40]:
a%2

array([[1, 0],
       [1, 0]])

In [42]:
a[1,0]

np.int64(3)

In [ ]:
a[[1,0]]

array([[3, 4],
       [1, 2]])

In [48]:
a[[1,0],[1,0]]

array([4, 1])

In [46]:
a[[[1,0],[1,0]]]

array([[[3, 4],
        [1, 2]],

       [[3, 4],
        [1, 2]]])

In [41]:
a[a%2]

array([[[3, 4],
        [1, 2]],

       [[3, 4],
        [1, 2]]])

In [52]:
xy = np.where(a >= 2, a, 0)

In [53]:
xy

array([[0, 2],
       [3, 4]])

In [30]:
u = np.sum(y, axis=0)
print(u)
u.ndim

[6]


1

In [68]:
u = np.random.default_rng()
u.random([1,2,3])
u.integers(low=5,high=11, size=(1,2))

array([[6, 5]])

In [33]:
v: np.ndarray = np.sum(y,axis=1)
print(v)
v.ndim

[1 2 3]


1

In [69]:
np.random.seed(42)

### <span style="color:orange"> Reading & Writing from Files </span>

In [ ]:
# NumPy provides the option of importing data from files directly into ndarray using the loadtxt function
# The savetxt function can be used to write data from an array into a text file
#import os
#print(os.listdir('../input'))
arr_txt = np.loadtxt('../input/data_file.txt')
np.savetxt('newfilex.txt', arr_txt)

ValueError: Some errors were detected !
    Line #3 (got 2 columns instead of 3)
    Line #4 (got 5 columns instead of 3)
    Line #5 (got 2 columns instead of 3)
    Line #6 (got 2 columns instead of 3)
    Line #7 (got 5 columns instead of 3)
    Line #8 (got 2 columns instead of 3)
    Line #9 (got 4 columns instead of 3)
    Line #10 (got 5 columns instead of 3)
    Line #11 (got 5 columns instead of 3)
    Line #12 (got 2 columns instead of 3)
    Line #13 (got 4 columns instead of 3)
    Line #14 (got 5 columns instead of 3)
    Line #15 (got 5 columns instead of 3)
    Line #17 (got 2 columns instead of 3)
    Line #18 (got 5 columns instead of 3)
    Line #20 (got 5 columns instead of 3)
    Line #22 (got 5 columns instead of 3)
    Line #23 (got 5 columns instead of 3)
    Line #24 (got 5 columns instead of 3)
    Line #27 (got 2 columns instead of 3)
    Line #28 (got 5 columns instead of 3)
    Line #29 (got 5 columns instead of 3)
    Line #31 (got 2 columns instead of 3)
    Line #32 (got 2 columns instead of 3)
    Line #33 (got 2 columns instead of 3)
    Line #34 (got 2 columns instead of 3)
    Line #35 (got 5 columns instead of 3)
    Line #37 (got 2 columns instead of 3)
    Line #39 (got 2 columns instead of 3)
    Line #41 (got 2 columns instead of 3)
    Line #42 (got 2 columns instead of 3)
    Line #45 (got 2 columns instead of 3)
    Line #46 (got 2 columns instead of 3)
    Line #47 (got 2 columns instead of 3)
    Line #49 (got 5 columns instead of 3)
    Line #50 (got 5 columns instead of 3)
    Line #51 (got 5 columns instead of 3)
    Line #52 (got 2 columns instead of 3)
    Line #54 (got 5 columns instead of 3)
    Line #57 (got 5 columns instead of 3)
    Line #58 (got 2 columns instead of 3)
    Line #59 (got 5 columns instead of 3)
    Line #60 (got 5 columns instead of 3)
    Line #63 (got 2 columns instead of 3)
    Line #64 (got 2 columns instead of 3)
    Line #65 (got 5 columns instead of 3)
    Line #66 (got 2 columns instead of 3)
    Line #67 (got 2 columns instead of 3)
    Line #68 (got 5 columns instead of 3)
    Line #69 (got 5 columns instead of 3)
    Line #70 (got 5 columns instead of 3)
    Line #71 (got 2 columns instead of 3)
    Line #72 (got 5 columns instead of 3)
    Line #73 (got 5 columns instead of 3)
    Line #74 (got 2 columns instead of 3)
    Line #75 (got 2 columns instead of 3)
    Line #76 (got 5 columns instead of 3)
    Line #77 (got 4 columns instead of 3)
    Line #78 (got 2 columns instead of 3)
    Line #80 (got 2 columns instead of 3)
    Line #81 (got 5 columns instead of 3)
    Line #82 (got 2 columns instead of 3)
    Line #83 (got 2 columns instead of 3)
    Line #84 (got 5 columns instead of 3)
    Line #85 (got 2 columns instead of 3)
    Line #86 (got 2 columns instead of 3)
    Line #87 (got 5 columns instead of 3)
    Line #90 (got 5 columns instead of 3)
    Line #91 (got 5 columns instead of 3)
    Line #92 (got 5 columns instead of 3)
    Line #93 (got 5 columns instead of 3)
    Line #94 (got 2 columns instead of 3)
    Line #96 (got 5 columns instead of 3)
    Line #99 (got 5 columns instead of 3)
    Line #100 (got 5 columns instead of 3)
    Line #102 (got 2 columns instead of 3)
    Line #103 (got 2 columns instead of 3)
    Line #104 (got 5 columns instead of 3)
    Line #105 (got 2 columns instead of 3)
    Line #106 (got 2 columns instead of 3)
    Line #107 (got 2 columns instead of 3)
    Line #108 (got 5 columns instead of 3)
    Line #109 (got 4 columns instead of 3)
    Line #110 (got 2 columns instead of 3)
    Line #111 (got 5 columns instead of 3)
    Line #112 (got 5 columns instead of 3)
    Line #113 (got 4 columns instead of 3)
    Line #114 (got 5 columns instead of 3)
    Line #115 (got 5 columns instead of 3)
    Line #116 (got 5 columns instead of 3)
    Line #117 (got 5 columns instead of 3)
    Line #118 (got 5 columns instead of 3)
    Line #119 (got 5 columns instead of 3)
    Line #120 (got 2 columns instead of 3)
    Line #123 (got 5 columns instead of 3)
    Line #124 (got 5 columns instead of 3)
    Line #125 (got 2 columns instead of 3)
    Line #126 (got 5 columns instead of 3)
    Line #127 (got 2 columns instead of 3)
    Line #128 (got 2 columns instead of 3)
    Line #129 (got 5 columns instead of 3)
    Line #130 (got 5 columns instead of 3)
    Line #131 (got 2 columns instead of 3)
    Line #132 (got 2 columns instead of 3)
    Line #133 (got 2 columns instead of 3)
    Line #134 (got 4 columns instead of 3)
    Line #135 (got 2 columns instead of 3)
    Line #136 (got 2 columns instead of 3)
    Line #138 (got 4 columns instead of 3)
    Line #139 (got 2 columns instead of 3)
    Line #140 (got 5 columns instead of 3)
    Line #141 (got 2 columns instead of 3)
    Line #142 (got 5 columns instead of 3)
    Line #143 (got 5 columns instead of 3)
    Line #144 (got 5 columns instead of 3)
    Line #146 (got 5 columns instead of 3)
    Line #147 (got 5 columns instead of 3)
    Line #148 (got 2 columns instead of 3)
    Line #149 (got 2 columns instead of 3)
    Line #150 (got 5 columns instead of 3)
    Line #151 (got 2 columns instead of 3)
    Line #152 (got 5 columns instead of 3)
    Line #153 (got 2 columns instead of 3)
    Line #156 (got 5 columns instead of 3)
    Line #157 (got 5 columns instead of 3)
    Line #158 (got 5 columns instead of 3)
    Line #160 (got 2 columns instead of 3)
    Line #161 (got 2 columns instead of 3)
    Line #162 (got 5 columns instead of 3)
    Line #163 (got 5 columns instead of 3)
    Line #166 (got 2 columns instead of 3)
    Line #167 (got 5 columns instead of 3)
    Line #168 (got 2 columns instead of 3)
    Line #169 (got 2 columns instead of 3)
    Line #170 (got 2 columns instead of 3)
    Line #171 (got 4 columns instead of 3)
    Line #172 (got 5 columns instead of 3)
    Line #173 (got 2 columns instead of 3)
    Line #175 (got 2 columns instead of 3)
    Line #177 (got 2 columns instead of 3)
    Line #178 (got 5 columns instead of 3)
    Line #179 (got 2 columns instead of 3)
    Line #180 (got 5 columns instead of 3)
    Line #181 (got 2 columns instead of 3)
    Line #182 (got 2 columns instead of 3)
    Line #183 (got 4 columns instead of 3)
    Line #184 (got 4 columns instead of 3)
    Line #186 (got 2 columns instead of 3)
    Line #187 (got 2 columns instead of 3)
    Line #188 (got 4 columns instead of 3)
    Line #189 (got 5 columns instead of 3)
    Line #190 (got 5 columns instead of 3)
    Line #191 (got 5 columns instead of 3)
    Line #193 (got 5 columns instead of 3)
    Line #195 (got 5 columns instead of 3)
    Line #196 (got 2 columns instead of 3)
    Line #197 (got 5 columns instead of 3)
    Line #198 (got 5 columns instead of 3)
    Line #199 (got 4 columns instead of 3)
    Line #200 (got 2 columns instead of 3)
    Line #201 (got 5 columns instead of 3)
    Line #203 (got 2 columns instead of 3)
    Line #204 (got 2 columns instead of 3)
    Line #205 (got 2 columns instead of 3)
    Line #206 (got 4 columns instead of 3)
    Line #207 (got 5 columns instead of 3)
    Line #208 (got 4 columns instead of 3)
    Line #209 (got 5 columns instead of 3)
    Line #210 (got 5 columns instead of 3)
    Line #211 (got 2 columns instead of 3)
    Line #213 (got 5 columns instead of 3)
    Line #216 (got 5 columns instead of 3)
    Line #217 (got 2 columns instead of 3)
    Line #218 (got 2 columns instead of 3)
    Line #219 (got 5 columns instead of 3)
    Line #220 (got 5 columns instead of 3)
    Line #221 (got 2 columns instead of 3)
    Line #223 (got 5 columns instead of 3)
    Line #225 (got 5 columns instead of 3)
    Line #226 (got 5 columns instead of 3)
    Line #227 (got 2 columns instead of 3)
    Line #228 (got 5 columns instead of 3)
    Line #232 (got 5 columns instead of 3)
    Line #233 (got 2 columns instead of 3)
    Line #235 (got 2 columns instead of 3)
    Line #236 (got 4 columns instead of 3)
    Line #237 (got 2 columns instead of 3)
    Line #238 (got 5 columns instead of 3)
    Line #239 (got 5 columns instead of 3)
    Line #241 (got 5 columns instead of 3)
    Line #242 (got 2 columns instead of 3)
    Line #243 (got 2 columns instead of 3)
    Line #245 (got 5 columns instead of 3)
    Line #246 (got 4 columns instead of 3)
    Line #247 (got 2 columns instead of 3)
    Line #248 (got 2 columns instead of 3)
    Line #249 (got 2 columns instead of 3)
    Line #250 (got 2 columns instead of 3)
    Line #251 (got 5 columns instead of 3)
    Line #252 (got 2 columns instead of 3)
    Line #253 (got 5 columns instead of 3)
    Line #256 (got 2 columns instead of 3)
    Line #257 (got 2 columns instead of 3)
    Line #259 (got 2 columns instead of 3)
    Line #260 (got 2 columns instead of 3)
    Line #261 (got 2 columns instead of 3)
    Line #262 (got 2 columns instead of 3)
    Line #263 (got 5 columns instead of 3)
    Line #264 (got 2 columns instead of 3)
    Line #267 (got 5 columns instead of 3)
    Line #268 (got 5 columns instead of 3)
    Line #269 (got 5 columns instead of 3)
    Line #270 (got 4 columns instead of 3)
    Line #271 (got 2 columns instead of 3)
    Line #273 (got 4 columns instead of 3)
    Line #274 (got 2 columns instead of 3)
    Line #275 (got 5 columns instead of 3)
    Line #276 (got 5 columns instead of 3)
    Line #277 (got 5 columns instead of 3)
    Line #280 (got 2 columns instead of 3)
    Line #281 (got 5 columns instead of 3)
    Line #282 (got 2 columns instead of 3)
    Line #283 (got 2 columns instead of 3)
    Line #286 (got 5 columns instead of 3)
    Line #287 (got 5 columns instead of 3)
    Line #288 (got 2 columns instead of 3)
    Line #289 (got 2 columns instead of 3)
    Line #290 (got 5 columns instead of 3)
    Line #291 (got 2 columns instead of 3)
    Line #292 (got 5 columns instead of 3)
    Line #293 (got 5 columns instead of 3)
    Line #295 (got 2 columns instead of 3)
    Line #297 (got 2 columns instead of 3)
    Line #298 (got 2 columns instead of 3)
    Line #299 (got 2 columns instead of 3)
    Line #300 (got 5 columns instead of 3)
    Line #301 (got 5 columns instead of 3)
    Line #302 (got 2 columns instead of 3)
    Line #303 (got 5 columns instead of 3)
    Line #304 (got 5 columns instead of 3)
    Line #305 (got 5 columns instead of 3)
    Line #309 (got 5 columns instead of 3)
    Line #312 (got 5 columns instead of 3)
    Line #314 (got 2 columns instead of 3)
    Line #315 (got 5 columns instead of 3)
    Line #316 (got 5 columns instead of 3)
    Line #317 (got 5 columns instead of 3)
    Line #318 (got 5 columns instead of 3)
    Line #320 (got 2 columns instead of 3)
    Line #322 (got 5 columns instead of 3)
    Line #324 (got 5 columns instead of 3)
    Line #325 (got 2 columns instead of 3)
    Line #326 (got 5 columns instead of 3)
    Line #328 (got 5 columns instead of 3)
    Line #329 (got 4 columns instead of 3)
    Line #330 (got 5 columns instead of 3)
    Line #332 (got 2 columns instead of 3)
    Line #333 (got 5 columns instead of 3)
    Line #334 (got 2 columns instead of 3)
    Line #336 (got 5 columns instead of 3)
    Line #339 (got 5 columns instead of 3)
    Line #344 (got 2 columns instead of 3)
    Line #345 (got 2 columns instead of 3)
    Line #346 (got 5 columns instead of 3)
    Line #348 (got 5 columns instead of 3)
    Line #349 (got 5 columns instead of 3)
    Line #350 (got 5 columns instead of 3)
    Line #353 (got 2 columns instead of 3)
    Line #354 (got 2 columns instead of 3)
    Line #355 (got 2 columns instead of 3)
    Line #356 (got 4 columns instead of 3)
    Line #357 (got 2 columns instead of 3)
    Line #358 (got 5 columns instead of 3)
    Line #359 (got 4 columns instead of 3)
    Line #360 (got 5 columns instead of 3)
    Line #361 (got 2 columns instead of 3)
    Line #362 (got 5 columns instead of 3)
    Line #363 (got 5 columns instead of 3)
    Line #365 (got 2 columns instead of 3)
    Line #366 (got 5 columns instead of 3)
    Line #367 (got 5 columns instead of 3)
    Line #368 (got 2 columns instead of 3)
    Line #369 (got 5 columns instead of 3)
    Line #370 (got 5 columns instead of 3)
    Line #372 (got 2 columns instead of 3)
    Line #373 (got 2 columns instead of 3)
    Line #375 (got 5 columns instead of 3)
    Line #377 (got 4 columns instead of 3)
    Line #379 (got 5 columns instead of 3)
    Line #380 (got 2 columns instead of 3)
    Line #381 (got 5 columns instead of 3)
    Line #383 (got 2 columns instead of 3)
    Line #384 (got 2 columns instead of 3)
    Line #385 (got 2 columns instead of 3)
    Line #386 (got 5 columns instead of 3)
    Line #387 (got 5 columns instead of 3)
    Line #388 (got 5 columns instead of 3)
    Line #389 (got 5 columns instead of 3)
    Line #391 (got 5 columns instead of 3)
    Line #392 (got 2 columns instead of 3)
    Line #393 (got 2 columns instead of 3)
    Line #394 (got 5 columns instead of 3)
    Line #395 (got 2 columns instead of 3)
    Line #396 (got 5 columns instead of 3)
    Line #397 (got 5 columns instead of 3)
    Line #398 (got 2 columns instead of 3)
    Line #399 (got 2 columns instead of 3)
    Line #400 (got 2 columns instead of 3)
    Line #401 (got 5 columns instead of 3)
    Line #402 (got 5 columns instead of 3)
    Line #403 (got 5 columns instead of 3)
    Line #404 (got 5 columns instead of 3)
    Line #405 (got 4 columns instead of 3)
    Line #406 (got 2 columns instead of 3)
    Line #407 (got 5 columns instead of 3)
    Line #409 (got 2 columns instead of 3)
    Line #412 (got 2 columns instead of 3)
    Line #414 (got 5 columns instead of 3)
    Line #415 (got 5 columns instead of 3)
    Line #416 (got 2 columns instead of 3)
    Line #417 (got 2 columns instead of 3)
    Line #418 (got 2 columns instead of 3)
    Line #419 (got 5 columns instead of 3)
    Line #421 (got 5 columns instead of 3)
    Line #422 (got 2 columns instead of 3)
    Line #423 (got 2 columns instead of 3)
    Line #424 (got 5 columns instead of 3)
    Line #425 (got 2 columns instead of 3)
    Line #426 (got 5 columns instead of 3)
    Line #427 (got 5 columns instead of 3)
    Line #428 (got 2 columns instead of 3)
    Line #429 (got 5 columns instead of 3)
    Line #430 (got 5 columns instead of 3)
    Line #431 (got 2 columns instead of 3)
    Line #432 (got 2 columns instead of 3)
    Line #433 (got 5 columns instead of 3)
    Line #434 (got 2 columns instead of 3)
    Line #436 (got 5 columns instead of 3)
    Line #437 (got 2 columns instead of 3)
    Line #439 (got 5 columns instead of 3)
    Line #440 (got 2 columns instead of 3)
    Line #443 (got 5 columns instead of 3)
    Line #444 (got 5 columns instead of 3)
    Line #445 (got 2 columns instead of 3)
    Line #446 (got 2 columns instead of 3)
    Line #448 (got 5 columns instead of 3)
    Line #449 (got 5 columns instead of 3)
    Line #450 (got 5 columns instead of 3)
    Line #451 (got 2 columns instead of 3)
    Line #452 (got 2 columns instead of 3)
    Line #454 (got 2 columns instead of 3)
    Line #455 (got 4 columns instead of 3)
    Line #456 (got 2 columns instead of 3)
    Line #457 (got 5 columns instead of 3)
    Line #458 (got 5 columns instead of 3)
    Line #459 (got 5 columns instead of 3)
    Line #460 (got 5 columns instead of 3)
    Line #461 (got 2 columns instead of 3)
    Line #464 (got 2 columns instead of 3)
    Line #466 (got 2 columns instead of 3)
    Line #467 (got 2 columns instead of 3)
    Line #468 (got 5 columns instead of 3)
    Line #469 (got 5 columns instead of 3)
    Line #470 (got 2 columns instead of 3)
    Line #471 (got 2 columns instead of 3)
    Line #474 (got 2 columns instead of 3)
    Line #475 (got 2 columns instead of 3)
    Line #476 (got 5 columns instead of 3)
    Line #477 (got 4 columns instead of 3)
    Line #478 (got 4 columns instead of 3)
    Line #481 (got 5 columns instead of 3)
    Line #483 (got 2 columns instead of 3)
    Line #484 (got 5 columns instead of 3)
    Line #485 (got 5 columns instead of 3)
    Line #486 (got 5 columns instead of 3)
    Line #487 (got 5 columns instead of 3)
    Line #488 (got 5 columns instead of 3)
    Line #489 (got 4 columns instead of 3)
    Line #490 (got 5 columns instead of 3)
    Line #491 (got 4 columns instead of 3)
    Line #493 (got 4 columns instead of 3)
    Line #494 (got 5 columns instead of 3)
    Line #495 (got 5 columns instead of 3)
    Line #496 (got 5 columns instead of 3)
    Line #498 (got 5 columns instead of 3)
    Line #499 (got 5 columns instead of 3)
    Line #500 (got 5 columns instead of 3)
    Line #501 (got 2 columns instead of 3)
    Line #502 (got 2 columns instead of 3)
    Line #503 (got 5 columns instead of 3)
    Line #504 (got 2 columns instead of 3)
    Line #505 (got 5 columns instead of 3)
    Line #507 (got 2 columns instead of 3)
    Line #508 (got 2 columns instead of 3)
    Line #509 (got 5 columns instead of 3)
    Line #510 (got 2 columns instead of 3)
    Line #511 (got 4 columns instead of 3)
    Line #513 (got 2 columns instead of 3)
    Line #514 (got 2 columns instead of 3)
    Line #515 (got 2 columns instead of 3)
    Line #516 (got 5 columns instead of 3)
    Line #517 (got 2 columns instead of 3)
    Line #518 (got 5 columns instead of 3)
    Line #519 (got 5 columns instead of 3)
    Line #522 (got 2 columns instead of 3)
    Line #523 (got 5 columns instead of 3)
    Line #524 (got 5 columns instead of 3)
    Line #525 (got 5 columns instead of 3)
    Line #527 (got 5 columns instead of 3)
    Line #528 (got 2 columns instead of 3)
    Line #530 (got 2 columns instead of 3)
    Line #531 (got 2 columns instead of 3)
    Line #532 (got 2 columns instead of 3)
    Line #533 (got 2 columns instead of 3)
    Line #534 (got 5 columns instead of 3)
    Line #535 (got 2 columns instead of 3)
    Line #537 (got 2 columns instead of 3)
    Line #538 (got 5 columns instead of 3)
    Line #539 (got 5 columns instead of 3)
    Line #540 (got 2 columns instead of 3)
    Line #541 (got 5 columns instead of 3)
    Line #542 (got 2 columns instead of 3)
    Line #543 (got 5 columns instead of 3)
    Line #544 (got 5 columns instead of 3)
    Line #545 (got 5 columns instead of 3)
    Line #546 (got 5 columns instead of 3)
    Line #547 (got 4 columns instead of 3)
    Line #548 (got 5 columns instead of 3)
    Line #549 (got 5 columns instead of 3)
    Line #550 (got 2 columns instead of 3)
    Line #551 (got 2 columns instead of 3)
    Line #552 (got 2 columns instead of 3)
    Line #554 (got 5 columns instead of 3)
    Line #555 (got 5 columns instead of 3)
    Line #557 (got 2 columns instead of 3)
    Line #558 (got 2 columns instead of 3)
    Line #559 (got 5 columns instead of 3)
    Line #562 (got 2 columns instead of 3)
    Line #563 (got 5 columns instead of 3)
    Line #564 (got 5 columns instead of 3)
    Line #565 (got 5 columns instead of 3)
    Line #566 (got 2 columns instead of 3)
    Line #567 (got 2 columns instead of 3)
    Line #568 (got 2 columns instead of 3)
    Line #569 (got 2 columns instead of 3)
    Line #571 (got 2 columns instead of 3)
    Line #572 (got 4 columns instead of 3)
    Line #575 (got 2 columns instead of 3)
    Line #576 (got 2 columns instead of 3)
    Line #578 (got 2 columns instead of 3)
    Line #580 (got 5 columns instead of 3)
    Line #581 (got 2 columns instead of 3)
    Line #582 (got 5 columns instead of 3)
    Line #583 (got 5 columns instead of 3)
    Line #584 (got 5 columns instead of 3)
    Line #585 (got 5 columns instead of 3)
    Line #586 (got 2 columns instead of 3)
    Line #588 (got 5 columns instead of 3)
    Line #589 (got 2 columns instead of 3)
    Line #590 (got 2 columns instead of 3)
    Line #591 (got 2 columns instead of 3)
    Line #592 (got 4 columns instead of 3)
    Line #594 (got 5 columns instead of 3)
    Line #597 (got 2 columns instead of 3)
    Line #600 (got 2 columns instead of 3)
    Line #601 (got 5 columns instead of 3)
    Line #603 (got 2 columns instead of 3)
    Line #604 (got 4 columns instead of 3)
    Line #606 (got 5 columns instead of 3)
    Line #608 (got 2 columns instead of 3)
    Line #609 (got 5 columns instead of 3)
    Line #610 (got 5 columns instead of 3)
    Line #611 (got 5 columns instead of 3)
    Line #612 (got 2 columns instead of 3)
    Line #614 (got 2 columns instead of 3)
    Line #616 (got 5 columns instead of 3)
    Line #617 (got 4 columns instead of 3)
    Line #618 (got 2 columns instead of 3)
    Line #619 (got 2 columns instead of 3)
    Line #620 (got 2 columns instead of 3)
    Line #621 (got 2 columns instead of 3)
    Line #622 (got 5 columns instead of 3)
    Line #623 (got 2 columns instead of 3)
    Line #624 (got 5 columns instead of 3)
    Line #625 (got 4 columns instead of 3)
    Line #626 (got 2 columns instead of 3)
    Line #627 (got 5 columns instead of 3)
    Line #628 (got 5 columns instead of 3)
    Line #631 (got 5 columns instead of 3)
    Line #632 (got 2 columns instead of 3)
    Line #633 (got 5 columns instead of 3)
    Line #635 (got 2 columns instead of 3)
    Line #639 (got 2 columns instead of 3)
    Line #640 (got 5 columns instead of 3)
    Line #641 (got 2 columns instead of 3)
    Line #642 (got 5 columns instead of 3)
    Line #643 (got 5 columns instead of 3)
    Line #644 (got 5 columns instead of 3)
    Line #645 (got 4 columns instead of 3)
    Line #646 (got 2 columns instead of 3)
    Line #648 (got 5 columns instead of 3)
    Line #649 (got 5 columns instead of 3)
    Line #650 (got 5 columns instead of 3)
    Line #651 (got 2 columns instead of 3)
    Line #652 (got 2 columns instead of 3)
    Line #654 (got 2 columns instead of 3)
    Line #655 (got 5 columns instead of 3)
    Line #656 (got 2 columns instead of 3)
    Line #658 (got 5 columns instead of 3)
    Line #659 (got 2 columns instead of 3)
    Line #660 (got 2 columns instead of 3)
    Line #661 (got 4 columns instead of 3)
    Line #662 (got 5 columns instead of 3)
    Line #664 (got 5 columns instead of 3)
    Line #665 (got 2 columns instead of 3)
    Line #667 (got 5 columns instead of 3)
    Line #669 (got 2 columns instead of 3)
    Line #670 (got 2 columns instead of 3)
    Line #671 (got 2 columns instead of 3)
    Line #672 (got 5 columns instead of 3)
    Line #673 (got 2 columns instead of 3)
    Line #674 (got 2 columns instead of 3)
    Line #675 (got 5 columns instead of 3)
    Line #677 (got 2 columns instead of 3)
    Line #678 (got 4 columns instead of 3)
    Line #680 (got 2 columns instead of 3)
    Line #681 (got 5 columns instead of 3)
    Line #682 (got 5 columns instead of 3)
    Line #683 (got 5 columns instead of 3)
    Line #684 (got 2 columns instead of 3)
    Line #685 (got 2 columns instead of 3)
    Line #686 (got 5 columns instead of 3)
    Line #687 (got 2 columns instead of 3)
    Line #688 (got 2 columns instead of 3)
    Line #689 (got 2 columns instead of 3)
    Line #690 (got 5 columns instead of 3)
    Line #691 (got 2 columns instead of 3)
    Line #692 (got 2 columns instead of 3)
    Line #693 (got 5 columns instead of 3)
    Line #694 (got 5 columns instead of 3)
    Line #695 (got 2 columns instead of 3)
    Line #697 (got 5 columns instead of 3)
    Line #698 (got 2 columns instead of 3)
    Line #699 (got 2 columns instead of 3)
    Line #702 (got 4 columns instead of 3)
    Line #704 (got 2 columns instead of 3)
    Line #705 (got 5 columns instead of 3)
    Line #706 (got 5 columns instead of 3)
    Line #707 (got 5 columns instead of 3)
    Line #708 (got 2 columns instead of 3)
    Line #710 (got 5 columns instead of 3)
    Line #711 (got 5 columns instead of 3)
    Line #712 (got 4 columns instead of 3)
    Line #717 (got 2 columns instead of 3)
    Line #718 (got 4 columns instead of 3)
    Line #719 (got 5 columns instead of 3)
    Line #720 (got 5 columns instead of 3)
    Line #721 (got 5 columns instead of 3)
    Line #722 (got 4 columns instead of 3)
    Line #723 (got 5 columns instead of 3)
    Line #725 (got 2 columns instead of 3)
    Line #726 (got 5 columns instead of 3)
    Line #727 (got 2 columns instead of 3)
    Line #729 (got 2 columns instead of 3)
    Line #730 (got 5 columns instead of 3)
    Line #731 (got 5 columns instead of 3)
    Line #732 (got 2 columns instead of 3)
    Line #733 (got 5 columns instead of 3)
    Line #735 (got 5 columns instead of 3)
    Line #736 (got 2 columns instead of 3)
    Line #737 (got 2 columns instead of 3)
    Line #738 (got 2 columns instead of 3)
    Line #740 (got 5 columns instead of 3)
    Line #741 (got 2 columns instead of 3)
    Line #743 (got 4 columns instead of 3)
    Line #744 (got 5 columns instead of 3)
    Line #745 (got 5 columns instead of 3)
    Line #746 (got 2 columns instead of 3)
    Line #747 (got 5 columns instead of 3)
    Line #748 (got 5 columns instead of 3)
    Line #749 (got 5 columns instead of 3)
    Line #751 (got 5 columns instead of 3)
    Line #753 (got 5 columns instead of 3)
    Line #754 (got 2 columns instead of 3)
    Line #758 (got 5 columns instead of 3)
    Line #759 (got 5 columns instead of 3)
    Line #760 (got 5 columns instead of 3)
    Line #761 (got 5 columns instead of 3)
    Line #762 (got 2 columns instead of 3)
    Line #763 (got 2 columns instead of 3)
    Line #764 (got 2 columns instead of 3)
    Line #765 (got 2 columns instead of 3)
    Line #766 (got 5 columns instead of 3)
    Line #767 (got 2 columns instead of 3)
    Line #768 (got 5 columns instead of 3)
    Line #769 (got 2 columns instead of 3)
    Line #770 (got 5 columns instead of 3)
    Line #771 (got 5 columns instead of 3)
    Line #772 (got 5 columns instead of 3)
    Line #773 (got 4 columns instead of 3)
    Line #774 (got 5 columns instead of 3)
    Line #775 (got 5 columns instead of 3)
    Line #777 (got 5 columns instead of 3)
    Line #778 (got 2 columns instead of 3)
    Line #779 (got 4 columns instead of 3)
    Line #780 (got 2 columns instead of 3)
    Line #781 (got 5 columns instead of 3)
    Line #782 (got 2 columns instead of 3)
    Line #783 (got 5 columns instead of 3)
    Line #784 (got 2 columns instead of 3)
    Line #786 (got 2 columns instead of 3)
    Line #788 (got 2 columns instead of 3)
    Line #789 (got 2 columns instead of 3)
    Line #790 (got 5 columns instead of 3)
    Line #792 (got 2 columns instead of 3)
    Line #793 (got 2 columns instead of 3)
    Line #795 (got 4 columns instead of 3)
    Line #796 (got 5 columns instead of 3)
    Line #797 (got 5 columns instead of 3)
    Line #801 (got 2 columns instead of 3)
    Line #802 (got 2 columns instead of 3)
    Line #803 (got 2 columns instead of 3)
    Line #804 (got 5 columns instead of 3)
    Line #805 (got 2 columns instead of 3)
    Line #807 (got 5 columns instead of 3)
    Line #808 (got 2 columns instead of 3)
    Line #809 (got 2 columns instead of 3)
    Line #810 (got 2 columns instead of 3)
    Line #812 (got 2 columns instead of 3)
    Line #813 (got 2 columns instead of 3)
    Line #814 (got 4 columns instead of 3)
    Line #815 (got 2 columns instead of 3)
    Line #816 (got 5 columns instead of 3)
    Line #818 (got 2 columns instead of 3)
    Line #819 (got 2 columns instead of 3)
    Line #820 (got 5 columns instead of 3)
    Line #821 (got 4 columns instead of 3)
    Line #822 (got 2 columns instead of 3)
    Line #823 (got 5 columns instead of 3)
    Line #824 (got 2 columns instead of 3)
    Line #825 (got 2 columns instead of 3)
    Line #826 (got 5 columns instead of 3)
    Line #827 (got 2 columns instead of 3)
    Line #828 (got 5 columns instead of 3)
    Line #830 (got 2 columns instead of 3)
    Line #832 (got 5 columns instead of 3)
    Line #833 (got 5 columns instead of 3)
    Line #834 (got 2 columns instead of 3)
    Line #836 (got 2 columns instead of 3)
    Line #837 (got 2 columns instead of 3)
    Line #838 (got 2 columns instead of 3)
    Line #840 (got 5 columns instead of 3)
    Line #841 (got 5 columns instead of 3)
    Line #842 (got 2 columns instead of 3)
    Line #843 (got 5 columns instead of 3)
    Line #844 (got 2 columns instead of 3)
    Line #845 (got 5 columns instead of 3)
    Line #846 (got 2 columns instead of 3)
    Line #847 (got 2 columns instead of 3)
    Line #848 (got 5 columns instead of 3)
    Line #849 (got 4 columns instead of 3)
    Line #850 (got 2 columns instead of 3)
    Line #851 (got 2 columns instead of 3)
    Line #852 (got 2 columns instead of 3)
    Line #854 (got 5 columns instead of 3)
    Line #856 (got 2 columns instead of 3)
    Line #857 (got 2 columns instead of 3)
    Line #858 (got 2 columns instead of 3)
    Line #860 (got 5 columns instead of 3)
    Line #861 (got 2 columns instead of 3)
    Line #862 (got 2 columns instead of 3)
    Line #864 (got 2 columns instead of 3)
    Line #865 (got 2 columns instead of 3)
    Line #866 (got 5 columns instead of 3)
    Line #867 (got 5 columns instead of 3)
    Line #868 (got 2 columns instead of 3)
    Line #869 (got 2 columns instead of 3)
    Line #870 (got 5 columns instead of 3)
    Line #873 (got 2 columns instead of 3)
    Line #874 (got 5 columns instead of 3)
    Line #875 (got 2 columns instead of 3)
    Line #876 (got 2 columns instead of 3)
    Line #877 (got 5 columns instead of 3)
    Line #880 (got 2 columns instead of 3)
    Line #881 (got 2 columns instead of 3)
    Line #882 (got 5 columns instead of 3)
    Line #883 (got 4 columns instead of 3)
    Line #884 (got 5 columns instead of 3)
    Line #885 (got 2 columns instead of 3)
    Line #886 (got 5 columns instead of 3)
    Line #889 (got 2 columns instead of 3)
    Line #891 (got 2 columns instead of 3)
    Line #892 (got 2 columns instead of 3)
    Line #894 (got 5 columns instead of 3)
    Line #897 (got 2 columns instead of 3)
    Line #899 (got 5 columns instead of 3)
    Line #900 (got 5 columns instead of 3)
    Line #901 (got 2 columns instead of 3)
    Line #902 (got 2 columns instead of 3)
    Line #903 (got 2 columns instead of 3)
    Line #904 (got 5 columns instead of 3)
    Line #905 (got 2 columns instead of 3)
    Line #906 (got 5 columns instead of 3)
    Line #907 (got 4 columns instead of 3)
    Line #908 (got 2 columns instead of 3)
    Line #909 (got 5 columns instead of 3)
    Line #910 (got 5 columns instead of 3)
    Line #911 (got 2 columns instead of 3)
    Line #912 (got 2 columns instead of 3)
    Line #913 (got 2 columns instead of 3)
    Line #914 (got 5 columns instead of 3)
    Line #916 (got 5 columns instead of 3)
    Line #917 (got 2 columns instead of 3)
    Line #918 (got 2 columns instead of 3)
    Line #919 (got 5 columns instead of 3)
    Line #920 (got 2 columns instead of 3)
    Line #921 (got 2 columns instead of 3)
    Line #922 (got 5 columns instead of 3)
    Line #924 (got 5 columns instead of 3)
    Line #925 (got 2 columns instead of 3)
    Line #926 (got 2 columns instead of 3)
    Line #928 (got 2 columns instead of 3)
    Line #929 (got 2 columns instead of 3)
    Line #930 (got 5 columns instead of 3)
    Line #931 (got 2 columns instead of 3)
    Line #932 (got 2 columns instead of 3)
    Line #933 (got 2 columns instead of 3)
    Line #934 (got 5 columns instead of 3)
    Line #935 (got 4 columns instead of 3)
    Line #936 (got 5 columns instead of 3)
    Line #937 (got 5 columns instead of 3)
    Line #939 (got 2 columns instead of 3)
    Line #940 (got 2 columns instead of 3)
    Line #941 (got 5 columns instead of 3)
    Line #942 (got 2 columns instead of 3)
    Line #943 (got 2 columns instead of 3)
    Line #944 (got 5 columns instead of 3)
    Line #945 (got 4 columns instead of 3)
    Line #946 (got 4 columns instead of 3)
    Line #947 (got 2 columns instead of 3)
    Line #948 (got 2 columns instead of 3)
    Line #950 (got 2 columns instead of 3)
    Line #951 (got 2 columns instead of 3)
    Line #952 (got 2 columns instead of 3)
    Line #953 (got 2 columns instead of 3)
    Line #954 (got 5 columns instead of 3)
    Line #955 (got 5 columns instead of 3)
    Line #956 (got 2 columns instead of 3)
    Line #957 (got 2 columns instead of 3)
    Line #958 (got 4 columns instead of 3)
    Line #959 (got 5 columns instead of 3)
    Line #962 (got 5 columns instead of 3)
    Line #963 (got 2 columns instead of 3)
    Line #964 (got 5 columns instead of 3)
    Line #966 (got 2 columns instead of 3)
    Line #967 (got 2 columns instead of 3)
    Line #968 (got 5 columns instead of 3)
    Line #970 (got 5 columns instead of 3)
    Line #971 (got 4 columns instead of 3)
    Line #972 (got 5 columns instead of 3)
    Line #973 (got 5 columns instead of 3)
    Line #974 (got 2 columns instead of 3)
    Line #975 (got 2 columns instead of 3)
    Line #976 (got 2 columns instead of 3)
    Line #978 (got 5 columns instead of 3)
    Line #979 (got 4 columns instead of 3)
    Line #980 (got 5 columns instead of 3)
    Line #981 (got 2 columns instead of 3)
    Line #982 (got 5 columns instead of 3)
    Line #983 (got 5 columns instead of 3)
    Line #984 (got 2 columns instead of 3)
    Line #985 (got 5 columns instead of 3)
    Line #986 (got 2 columns instead of 3)
    Line #987 (got 5 columns instead of 3)
    Line #988 (got 2 columns instead of 3)
    Line #989 (got 2 columns instead of 3)
    Line #991 (got 2 columns instead of 3)
    Line #992 (got 2 columns instead of 3)
    Line #993 (got 2 columns instead of 3)
    Line #995 (got 2 columns instead of 3)
    Line #997 (got 5 columns instead of 3)
    Line #999 (got 2 columns instead of 3)
    Line #1000 (got 2 columns instead of 3)
    Line #1001 (got 2 columns instead of 3)

In [140]:
arr_txt.shape

NameError: name 'arr_txt' is not defined

In [1]:
%pip install ordered_set

Note: you may need to restart the kernel to use updated packages.


In [ ]:
# NumPy arrays can be dumped into CSV files using the savetxt function and the comma delimiter
# The genfromtxt function can be used to read data from a CSV file into a NumPy array
arr_csv = np.genfromtxt('../input/Hurricanes.csv', delimiter = ',')
np.savetxt('newfilex.csv', arr_csv, delimiter = ',')

## <span style="color:blue"> Pandas </span>

Pandas is an open-source Python library providing efficient, easy-to-use data structure and data analysis tools. The name Pandas is derived from "Panel Data" - an Econometrics from Multidimensional Data. Pandas is well suited for many different kinds of data:
1. Tabular data with heterogeneously-type columns.
2. Ordered and unordered time series data.
3. Arbitary matrix data with row and column labels.
4. Any other form observational/statistical data sets. The data actually need not be labeled at all to be placed into a pandas data structure.

Pandas provides three data structure - all of which are build on top of the NumPy array - all the data structures are value-mutable
1. Series (1D) - labeled, homogenous array of immutable size
2. DataFrames (2D) - labeled, heterogeneously typed, size-mutable tabular data structures
3. Panels (3D) - Labeled, size-mutable array

In [ ]:
import pandas as pd

### <span style="color:orange"> Series </span>

1. A Series is a single-dimensional array structures that stores homogenous data i.e., data of a single type.
2. All the elements of a Series are value-mutable and size-immutable
3. Data can be of multiple data types such as ndarray, lists, constants, series, dict etc.
4. Indexes must be unique, hashable and have the same length as data. Defaults to np.arrange(n) if no index is passed.
5. Data type of each column; if none is mentioned, it will be inferred; automatically
6. Deep copies data, set to false as default

### <span style="color:orange"> Creating a Series </span>

In [71]:
import pandas as pd

In [72]:
# Creating an empty Series
series = pd.Series() # The Series() function creates a new Series
print(series)

Series([], dtype: object)


In [73]:
# Creating a series from an ndarray
# Note that indexes are a assigned automatically if not specifies
arr = np.array([10,20,30,40,50])
series1 = pd.Series(arr)
print(series1)

0    10
1    20
2    30
3    40
4    50
dtype: int64


In [74]:
# Creating a series from a Python dict
# Note that the keys of the dictionary are used to assign indexes during conversion
data = {'a':10, 'b':20, 'c':30}
series2 = pd.Series(data)
print(series2)

a    10
b    20
c    30
dtype: int64


In [75]:
# Retrieving a part of the series using slicing
print(series1[1:4])

1    20
2    30
3    40
dtype: int64


In [77]:
print(series2['a':'b'])

a    10
b    20
dtype: int64


### <span style="color:orange"> DataFrames </span>

1. A DataFrame is a 2D data structure in which data is aligned in a tabular fashion consisting of rows & columns
2. A DataFrame can be created using the following constructor - pandas.DataFrame(data, index, dtype, copy)
3. Data can be of multiple data types such as ndarray, list, constants, series, dict etc.
4. Index Row and column labels of the dataframe; defaults to np.arrange(n) if no index is passed
5. Data type of each column
6. Creates a deep copy of the data, set to false as default

### <span style="color:orange"> Creating a DataFrame </span>

In [87]:
# Converting a list into a DataFrame
list1 = [10, 20, 30, 40]
table = pd.DataFrame(list1)
print(table)

    0
0  10
1  20
2  30
3  40


In [79]:
# Creating a DataFrame from a list of dictionaries
data = [{'a':1, 'b':2}, {'a':2, 'b':4, 'c':8}]
table1 = pd.DataFrame(data)
print(table1)
# NaN (not a number) is stored in areas where no data is provided

   a  b    c
0  1  2  NaN
1  2  4  8.0


In [88]:
# Creating a DataFrame from a list of dictionaries and accompaying row indices
table2 = pd.DataFrame(data, index = ['first', 'second'])
# Dict keys become column lables
print(table2)

        a  b    c
first   1  2  NaN
second  2  4  8.0


In [91]:
# Converting a dictionary of series into a DataFrame
data1 = {'one':pd.Series([1,2,3], index = ['a', 'b', 'c']),
        'two':pd.Series([1,2,3,4], index = ['a', 'b', 'c', 'd'])}
table3 = pd.DataFrame(data1)
print(table3)
# the resultant index is the union of all the series indexes passed

   one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  NaN    4


### <span style="color:orange"> DataFrame - Addition & Deletion of Columns </span>

In [90]:
# A new column can be added to a DataFrame when the data is passed as a Series
table3['three'] = pd.Series([10,20,30], index = ['a', 'b', 'c'])
print(table3)

   one  two  three
a  1.0    1   10.0
b  2.0    2   20.0
c  3.0    3   30.0
d  NaN    4    NaN


In [83]:
# DataFrame columns can be deleted using the del() function
del table3['one']
print(table3)

   two  three
a    1   10.0
b    2   20.0
c    3   30.0
d    4    NaN


In [84]:
# DataFrame columns can be deleted using the pop() function
table3.pop('two')
print(table3)

   three
a   10.0
b   20.0
c   30.0
d    NaN


### <span style="color:orange"> DataFrame - Addition & Deletion of Rows </span>

In [92]:
# DataFrame rows can be selected by passing the row lable to the loc() function
print(table3.loc['c'])

one    3.0
two    3.0
Name: c, dtype: float64


In [93]:
# Row selection can also be done using the row index
print(table3.iloc[2])

one    3.0
two    3.0
Name: c, dtype: float64


In [ ]:
# The append() function can be used to add more rows to the DataFrame
data2 = {'one':pd.Series([1,2,3], index = ['a', 'b', 'c']),
        'two':pd.Series([1,2,3,4], index = ['a', 'b', 'c', 'd'])}
table5 = pd.DataFrame(data2)
table5['three'] = pd.Series([10,20,30], index = ['a', 'b', 'c'])
row = pd.DataFrame([[11,13],[17,19]], columns = ['two', 'three'])
table6 = table5.append(row)
print(table6)

In [ ]:
# The drop() function can be used to drop rows whose labels are provided
table7 = table6.drop('a')
print(table7)

### <span style="color:orange"> Importing & Exporting Data </span>

In [ ]:
# Data can be loaded into DataFrames from input data stored in the CSV format using the read_csv() function
table_csv = pd.read_csv('../input/Cars2015.csv')

In [ ]:
# Data present in DataFrames can be written to a CSV file using the to_csv() function
# If the specified path doesn't exist, a file of the same name is automatically created
table_csv.to_csv('newcars2015.csv')

In [ ]:
# Data can be loaded into DataFrames from input data stored in the Excelsheet format using read_excel()
sheet = pd.read_excel('cars2015.xlsx')

In [ ]:
# Data present in DataFrames can be written to a spreadsheet file using to_excel()
#If the specified path doesn't exist, a file of the same name is automatically created
sheet.to_excel('newcars2015.xlsx')

## <span style="color:blue"> Matplotlib </span>

1. Matplotlib is a Python library that is specially designed for the development of graphs, charts etc., in order to provide interactive data visualisation
2. Matplotlib is inspired from the MATLAB software and reproduces many of it's features

In [ ]:
# Import Matplotlib submodule for plotting
import matplotlib.pyplot as plt

### <span style="color:orange"> Plotting in Matplotlib </span>

In [ ]:
plt.plot([1,2,3,4]) # List of vertical co-ordinates of the points plotted
plt.show() # Displays plot
# Implicit X-axis values from 0 to (N-1) where N is the length of the list

In [ ]:
# We can specify the values for both axes
x = range(5) # Sequence of values for the x-axis
# X-axis values specified - [0,1,2,3,4]
plt.plot(x, [x1**2 for x1 in x]) # vertical co-ordinates of the points plotted: y = x^2
plt.show()

In [ ]:
# We can use NumPy to specify the values for both axes with greater precision
x = np.arange(0, 5, 0.01)
plt.plot(x, [x1**2 for x1 in x]) # vertical co-ordinates of the points plotted: y = x^2
plt.show()

### <span style="color:orange"> Multiline Plots </span>

In [ ]:
# Multiple functions can be drawn on the same plot
x = range(5)
plt.plot(x, [x1 for x1 in x])
plt.plot(x, [x1*x1 for x1 in x])
plt.plot(x, [x1*x1*x1 for x1 in x])
plt.show()

In [ ]:
# Different colours are used for different lines
x = range(5)
plt.plot(x, [x1 for x1 in x],
         x, [x1*x1 for x1 in x],
         x, [x1*x1*x1 for x1 in x])
plt.show()

### <span style="color:orange"> Grids </span>

In [ ]:
# The grid() function adds a grid to the plot
# grid() takes a single Boolean parameter
# grid appears in the background of the plot
x = range(5)
plt.plot(x, [x1 for x1 in x],
         x, [x1*2 for x1 in x],
         x, [x1*4 for x1 in x])
plt.grid(True)
plt.show()

### <span style="color:orange"> Limiting the Axes </span>

In [ ]:
# The scale of the plot can be set using axis()
x = range(5)
plt.plot(x, [x1 for x1 in x],
         x, [x1*2 for x1 in x],
         x, [x1*4 for x1 in x])
plt.grid(True)
plt.axis([-1, 5, -1, 10]) # Sets new axes limits
plt.show()

In [ ]:
# The scale of the plot can also be set using xlim() and ylim()
x = range(5)
plt.plot(x, [x1 for x1 in x],
         x, [x1*2 for x1 in x],
         x, [x1*4 for x1 in x])
plt.grid(True)
plt.xlim(-1, 5)
plt.ylim(-1, 10)
plt.show()

### <span style="color:orange"> Adding Labels </span>

In [ ]:
# Labels can be added to the axes of the plot
x = range(5)
plt.plot(x, [x1 for x1 in x],
         x, [x1*2 for x1 in x],
         x, [x1*4 for x1 in x])
plt.grid(True)
plt.xlabel('X-axis')
plt.ylabel('Y-axis')
plt.show()

### <span style="color:orange"> Adding the Title </span>

In [ ]:
# The title defines the data plotted on the graph
x = range(5)
plt.plot(x, [x1 for x1 in x],
         x, [x1*2 for x1 in x],
         x, [x1*4 for x1 in x])
plt.grid(True)
plt.xlabel('X-axis')
plt.ylabel('Y-axis')
plt.title("Polynomial Graph") # Pass the title as a parameter to title()
plt.show()

### <span style="color:orange"> Adding a Legend </span>

In [ ]:
# Legends explain the meaning of each line in the graph
x = np.arange(5)
plt.plot(x, x, label = 'linear')
plt.plot(x, x*x, label = 'square')
plt.plot(x, x*x*x, label = 'cube')
plt.grid(True)
plt.xlabel('X-axis')
plt.ylabel('Y-axis')
plt.title("Polynomial Graph")
plt.legend()
plt.show()

### <span style="color:orange"> Adding a Markers </span>

In [ ]:
x = [1, 2, 3, 4, 5, 6]
y = [11, 22, 33, 44, 55, 66]
plt.plot(x, y, 'bo')
for i in range(len(x)):
    x_cord = x[i]
    y_cord = y[i]
    plt.text(x_cord, y_cord, (x_cord, y_cord), fontsize = 10)
plt.show()

### <span style="color:orange"> Saving Plots </span>

In [ ]:
# Plots can be saved using savefig()
x = np.arange(5)
plt.plot(x, x, label = 'linear')
plt.plot(x, x*x, label = 'square')
plt.plot(x, x*x*x, label = 'cube')
plt.grid(True)
plt.xlabel('X-axis')
plt.ylabel('Y-axis')
plt.title("Polynomial Graph")
plt.legend()
plt.savefig('plot.png') # Saves an image names 'plot.png' in the current directory
plt.show()

### <span style="color:orange"> Plot Types </span>

Matplotlib provides many types of plot formats for visualising information
1. Scatter Plot
2. Histogram
3. Bar Graph
4. Pie Chart

### <span style="color:orange"> Histogram </span>

In [ ]:
# Histograms display the distribution of a variable over a range of frequencies or values
y = np.random.randn(100, 100) # 100x100 array of a Gaussian distribution
plt.hist(y) # Function to plot the histogram takes the dataset as the parameter
plt.show()

In [ ]:
# Histogram groups values into non-overlapping categories called bins
# Default bin value of the histogram plot is 10
y = np.random.randn(1000)
plt.hist(y, 100)
plt.show()

### <span style="color:orange"> Bar Chart </span>

In [ ]:
# Bar charts are used to visually compare two or more values using rectangular bars
# Default width of each bar is 0.8 units
# [1,2,3] Mid-point of the lower face of every bar
# [1,4,9] Heights of the successive bars in the plot
plt.bar([1,2,3], [1,4,9])
plt.show()

In [ ]:
dictionary = {'A':25, 'B':70, 'C':55, 'D':90}
for i, key in enumerate(dictionary):
    plt.bar(i, dictionary[key]) # Each key-value pair is plotted individually as dictionaries are not iterable
plt.show()

In [ ]:
dictionary = {'A':25, 'B':70, 'C':55, 'D':90}
for i, key in enumerate(dictionary):
    plt.bar(i, dictionary[key])
plt.xticks(np.arange(len(dictionary)), dictionary.keys()) # Adds the keys as labels on the x-axis
plt.show()

### <span style="color:orange"> Pie Chart </span>

In [ ]:
plt.figure(figsize = (3,3)) # Size of the plot in inches
x = [40, 20, 5] # Proportions of the sectors
labels = ['Bikes', 'Cars', 'Buses']
plt.pie(x, labels = labels)
plt.show()

### <span style="color:orange"> Scatter Plot </span>

In [ ]:
# Scatter plots display values for two sets of data, visualised as a collection of points
# Two Gaussion distribution plotted
x = np.random.rand(1000)
y = np.random.rand(1000)
plt.scatter(x, y)
plt.show()

### <span style="color:orange"> Styling </span>

In [ ]:
# Matplotlib allows to choose custom colours for plots
y = np.arange(1, 3)
plt.plot(y, 'y') # Specifying line colours
plt.plot(y+5, 'm')
plt.plot(y+10, 'c')
plt.show()

Color code:
1. b = Blue
2. c = Cyan
3. g = Green
4. k = Black
5. m = Magenta
6. r = Red
7. w = White
8. y = Yellow

In [ ]:
# Matplotlib allows different line styles for plots
y = np.arange(1, 100)
plt.plot(y, '--', y*5, '-.', y*10, ':')
plt.show()
# - Solid line
# -- Dashed line
# -. Dash-Dot line
# : Dotted Line

In [ ]:
# Matplotlib provides customization options for markers
y = np.arange(1, 3, 0.2)
plt.plot(y, '*',
        y+0.5, 'o',
        y+1, 'D',
        y+2, '^',
        y+3, 's') # Specifying line styling
plt.show()